name: 'common'
description: 'Common steps needed for workflows'

inputs:
  os:
    description: 'OS'
    default: 'ubuntu-latest'
  node_version:
    description: 'Node version'
    default: '12.x'

runs:
  using: "composite"
  steps:
    - name: Setup Node.js environment
      uses: actions/setup-node@v1
      with:
        node-version: ${{ inputs.node_version }}

    - name: Determine npm cache location
      id: npm-cache
      run: echo "::set-output name=dir::$(npm config get cache)"

    - name: Cache dependencies
      uses: actions/cache@v2
      env:
        cache-name: dependencies-cache
      with:
        path: ${{ steps.npm-cache.outputs.dir }}
        key: ${{ inputs.os }}-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ inputs.os }}-${{ env.cache-name }}-

    - name: Install dependencies
      run: npm ci