name: CI

on:
  push:
    branches:
      - stable
      - alpha
      - beta

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      matrix:
        node_version: [ '12.x' ]
        os: [ 'ubuntu-latest', 'windows-latest', 'macos-latest' ]

    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - uses: common@v1
        with:
          os: ${{ runner.os }}
          node_version: ${{ matrix.node_version }}

      - name: Build application
        run: npm run make

      - name: Upload build artifact(s)
        uses: actions/upload-artifact@v2
        if: ${{ success() }}
        with:
          name: packages
          path: ./out/make/**/*.{exe,deb,rpm,dmg,zip}
          # path: |
          #   ./out/make/**/*.exe
          #   ./out/make/**/*.deb
          #   ./out/make/**/*.rpm
          #   ./out/make/**/*.dmg
          #   ./out/make/**/*.zip

  release:
    if: ${{ success() }}
    needs: build
    runs-on: 'ubuntu-latest'
    timeout-minutes: 5
    strategy:
      matrix:
        node_version: [ '12.x' ]

    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - uses: common@v1
        with:
          os: ${{ runner.os }}
          node_version: ${{ matrix.node_version }}

      - name: Download build artifact(s)
        uses: actions/download-artifact@v2
        if: ${{ success() }}
        with:
          name: packages
          path: ./downloads

      - name: Configure GPG key
        env:
          GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
        run: |
          mkdir -p ~/.gnupg/
          printf "$GPG_SIGNING_KEY" | base64 --decode > ~/.gnupg/private.key
          gpg --import ~/.gnupg/private.key

      - name: Generate, sign and verify checksum for artifact(s)
        run: |
          shasum -a 256 ./downloads/**/*.{exe,deb,rpm,dmg,zip} > SHA256SUMS
          gpg --armor --output SHA256SUMS.gpg --detach-sig SHA256SUMS
          gpg --verify SHA256SUMS.gpg SHA256SUMS
          shasum -a 256 -c SHA256SUMS

      - name: Release application
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIT_AUTHOR_NAME: Kesavamoorthi Subramanian
          GIT_AUTHOR_EMAIL: k7moorthi@gmail.com
          GIT_COMMITTER_NAME: Kesavamoorthi Subramanian
          GIT_COMMITTER_EMAIL: k7moorthi@gmail.com
        run: |
          git config commit.gpgsign true
          npx semantic-release
