name: CI

on:
  push:
    branches:
      - stable
      - alpha
      - beta

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        node_version: [ 12.x ]

    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}

      - name: Determine npm cache location
        id: npm-cache
        run: echo "::set-output name=dir::$(npm config get cache)"

      - name: Cache dependencies
        uses: actions/cache@v2
        env:
          cache-name: dependencies-cache
        with:
          path: ${{ steps.npm-cache.outputs.dir }}
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-name }}-

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run make

      # - name: Configure GPG Key
      #   env:
      #     GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
      #   run: |
      #     mkdir -p ~/.gnupg/
      #     printf "$GPG_SIGNING_KEY" | base64 --decode > ~/.gnupg/private.key
      #     gpg --import ~/.gnupg/private.key

      - name: Release application
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          # GIT_AUTHOR_NAME: Kesavamoorthi Subramanian
          # GIT_AUTHOR_EMAIL: k7moorthi@gmail.com
          # GIT_COMMITTER_NAME: Kesavamoorthi Subramanian
          # GIT_COMMITTER_EMAIL: k7moorthi@gmail.com
        run: npx semantic-release
